FROM ubuntu:19.04

RUN groupadd -g 209 plone
RUN useradd --shell /bin/bash -u 913 -g 209 -o -c "Plone user" -m plone

ARG repo=buildout.iadelib
RUN mkdir -p /home/plone/.buildout/downloads \
  && mkdir -p /home/plone/.buildout/eggs

ENV HOME=/home/plone
COPY default.cfg /home/plone/.buildout/default.cfg
RUN chown -R plone:plone /home/plone
RUN apt-get update \
  && apt full-upgrade -y \
  && apt-get install -y --no-install-recommends \
   build-essential \
   libpq-dev \
   libreadline-dev \
   wget \
   git \
   subversion \
   libpcre3-dev \
   libssl-dev \
   libxml2-dev \
   libxslt1-dev \
   libbz2-dev \
   libffi-dev \
   libjpeg62-dev \
   libopenjp2-7-dev \
   zlib1g-dev \
   python-dev \
   python-pip \
   virtualenv \
   python \
   graphicsmagick \
   ghostscript \
   poppler-utils \
   ruby \
   libmagic1 \
   libjpeg62 \
   libopenjp2-7 \
   libpython3.6 \
   python3-uno \
   libreoffice-script-provider-python

RUN apt-get full-upgrade -y -q

RUN gem install docsplit \
  && ln -sf /usr/bin/virtualenv /usr/local/bin/virtualenv-2.7

USER plone
WORKDIR /home/plone/
RUN git clone https://github.com/affinitic/${repo}.git ${repo}

WORKDIR /home/plone/${repo}
RUN mkdir -p var/filestorage/ \
  && touch var/filestorage/Data.fs \
  && make buildout

WORKDIR /home/plone/
RUN rm -rf ${repo}
