FROM ubuntu:22.04

RUN groupadd -g 209 plone
RUN useradd --shell /bin/bash -u 913 -g 209 -o -c "Plone user" -m plone

ENV HOME=/home/plone
RUN apt-get -qy update \
  && apt full-upgrade -y \
  && apt-get install -y --no-install-recommends \
   bash-completion curl htop locales make ncurses-term software-properties-common telnet tzdata vim \
   build-essential \
   libpq-dev \
   libreadline-dev \
   wget \
   git \
   curl \
   subversion \
   libpcre3-dev \
   libssl-dev \
   libxml2-dev \
   libxslt1-dev \
   libbz2-dev \
   libffi-dev \
   libjpeg62-dev \
   libopenjp2-7-dev \
   zlib1g-dev \
   python2.7-dev \
   python2.7 \
   imagemagick \
   graphicsmagick \
   ghostscript \
   poppler-utils \
   ruby \
   libmagic1 \
   libjpeg62 \
   libopenjp2-7 \
   libpython3.6 \
   python3-uno \
   libldap2-dev \
   libldap-2.5.0 \
   libsasl2-dev \
  && rm -rf /tmp/* /var/tmp/*

RUN ln -sf /usr/share/zoneinfo/Europe/Brussels /etc/localtime
RUN echo "Europe/Brussels" > /etc/timezone; dpkg-reconfigure -f noninteractive tzdata

RUN  curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py && python2.7 get-pip.py

# ---------
# MS CORE FONTS
# ---------
# from http://askubuntu.com/a/25614
RUN echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections
RUN apt-get install -y --no-install-recommends fontconfig ttf-mscorefonts-installer
ADD localfonts.conf /etc/fonts/local.conf

COPY fonts/* /usr/share/fonts/truetype/

RUN fc-cache -f -v

RUN apt-get install -y \
   libreoffice \
   libreoffice-script-provider-python \
   cabextract \
   default-jre \
   libreoffice-java-common \
   lynx
  && apt-get clean autoclean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN gem install docsplit

USER plone
WORKDIR /home/plone/
RUN git clone https://github.com/affinitic/${repo}.git .
RUN mkdir -p /home/plone/.buildout/downloads/dist \
  && mkdir -p /home/plone/.buildout/eggs
COPY default.cfg /home/plone/.buildout/default.cfg

WORKDIR /home/plone/.buildout/downloads/dist
RUN wget https://eggs.imio.be/find-links/common/ZSI-2.1a2-imio1.tar.gz

WORKDIR /home/plone/
RUN mkdir -p var/filestorage/ \
  && touch var/filestorage/Data.fs \
  && make requirements.txt \
  && pip install -r requirements.txt \
  && /home/plone/.local/bin/buildout -t 60 -Nc docker.cfg \
  && rm -rf /home/plone/.buildout/downloads/ /home/plone/.cache

WORKDIR /home/plone/
RUN rm -rf parts var *.cfg *.txt *.sh *.py Makefile *.conf